name: CI_Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        # Using windows 2019 to fix https://github.com/vidalt/HGS-CVRP/issues/33
        os: [ "ubuntu-latest", "windows-2019", "macos-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: make bin on ${{ matrix.os }}
      run: | 
        mkdir build 
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
        make bin
    - name: test bin on ${{ matrix.os }}
      run: |
        cd build
        ctest -R bin --verbose
    - name: make lib on ${{ matrix.os }}
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
        make lib
    - name: test lib on ${{ matrix.os }}
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"        
        make lib_test_c
        ctest -R lib --verbose
